os: linux
dist: xenial
language: python
jobs:
  include:
    - stage: Test
      python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - stage: Docs
      python: "3.7"
      script:
        # automodapi_toctreedirnm is sensitive to being in docs/ dir; will fix in documenteer
        - cd docs && sphinx-build -b html -a -d _build/doctree . _build/html && cd ../
      after_success:
        - ltd upload --product "ltd-conveyor" --travis --dir docs/_build/html
    - stage: Deploy to PyPI
      python: "3.7"
      script: skip
      deploy:
        provider: pypi
        username: sqre-admin
        upload_docs: false
        distributions: sdist bdist_wheel
        password:
          # PyPI deployment credentials for sqre-admin
          secure: "cgdZynMCCAZmq/nBh4QnOsey60OtSjX//6ti69zAsWWxvEIX+IoCdmfHIRdpY9EQ2w42Vi/Qo+IZK5KvCQTBISzd/NI5kR9gyxpWr4REYb/1W2Igeby2702GPzD89J4y8+vXpggVOfwcIObHaN5wUYgeG932/2WxfllHRfcOtdujrxlYDLWQUd/VX/3QwZBsG2F6a2d8C0CqlgUXBJ/exLDUYchjHmPdilN0EefC5zs2hpoehzQkhlQJlNYWm8YxD/ni556lCPkyLXi8Z3Ol00SnRnvDAM3mu+s6ITS8TKq6PXUrTqpR8JaN/WAG9JQ3Ej+AYGyGwef6Ks2udEp1u1V2dbCY3qnBGvBnRByJ3ey3RALDIhPAMQ1x1vsDfMwKL7Wu0vSXSmjPDUBdHKFEpCec5F4uYfWBewhK79KVaWvt/r0qnz/baEtT+bImeQENyh2oRDJGn4SHKPZEsDGukSzbc1YLSVmHoLN989G8EZH+SDXOYCbA++gakmbromWhYW+01Oc4SQBuCZfgLOOvId5MQwBpoq5LI6pFmKSWo/F49lYJuq/AzJelauSU0tC6SJ0yMzkiz925/IUG58Np5Am3sFltutlC569ZFUFHnL/B8CmKTFwxyM3fMMueAbVqFIv6c4rVpdYs1RePYhxv2Y9I1eNNVjm6I6cgzYDxoxc="
        on:
          tags: true
          repo: lsst-sqre/ltd-conveyor
install:
  - pip install ".[dev]"
script:
  - 'pytest'
env:
  global:
    # PyPI deployment credentials
    - secure: Xhw5hMO/IEAjDb4v68e44NlZWct+xA3he3Yyq3oJddrxzgZPBzCpi60HkSqQCdxePvut9w/ZTS81eEUnc+7Ym2j+JqSB45Rtepe/CHM1l73tVfMG3GpELCvB6MDSgSvBxpNB+OxLM2yPsXYUIghSEQ0rQIIMoUrTvMVvxpAGNRvFjRSbSGgDUDssLB7oGBvfAWzNfCuW8uU55Youf4CPm9I9gfMro86YatRF0h/yWveomkuojy9lo9siOxi9y4lEdcN5nDoFotddhlmp2B54oaTHvFl/vPOON0uKkTgopCfLv+cplnhWEx7McjZBcc01M/s9k+oRE1UkXpgM5lmf7pfKdaV+YZ7rbw2QudSjx+p2SFnBbCT24GfHY8pCJuwz63rUDPOt2BtH9n4cdjkrhm76AOJy5mF5W2/m5yKU6uktNhzFkkWsa9iIAgYU9FIMweKEwQdtpymAnHaArP1YSOJfM7BYspIp30gAMjs+HKBJiyIRPGHEnqekN/Yt6fnI2L0Zw5n5SREWqtaG1ishim3QEZvrfcczIik1HQo2D4hqc/BszjEkE+70WJ4tdmQJ9bW1MBMtSGFfsETmuvYmC1oreRHs0PRxR4y3W3i2TV+fJPRKqyrQcxiBQvbnkOHyYgCW/wXQHDMJbpNt/qmVRVLSIq2Pz7IdM8CTbUa3jQc=
    - secure: NTEJa1wL27hu9LrSNELh18Zzfdr5dr76wEYJz+E04gixJ3R3XyaU4B8MAodMvAC8V1du1BhP3pZHYby6ZxnSOhPZvAZL4FbEFkOPs1oS/qgpam8sf5+HYplfNZ+3vKxz0yxPdPE/Ltk1gsVqgOtjXyX4VTaCNtoH++pYAXBxdkjoQ1CwgmT6fIBGliH+Kf6b7z1Br+DDycaslMnlWu0guWNRwPKs/M8VPL3C3wEE6zEbAPtaSDYaB4fLqLwaKrjiOxKsKIlOV8A+BLZMPUmq3jlnrv6f3Ic2PNluiDnOVf1xzKHogt6KX0JBUANYpsE3qVDXMI76Ulv0S+446Pp1hxla3qj8noDPZal0xKG8S94aKEN01+QnktXbezK61/ErI9JCUk9AinjtT6uOk6MjLSjD0sLSwsNjvB3Ba4T4GEa0KI34wbH1PSdJJX5wyXHawxPK3eGwgqOvnUQtJbXGmgbhq4O0UUWbwOg/M7sf2Sb/85wZtwf5Ok134t9Uq0QJFyq+m+Hy8Yo+iKDAVXaok3ZQ7LIdC4EnnuFUOR6Kg3VIVu4zdiuLMmDUfR2pXhlS1+Ac9KGwuDePgBAW9lCKWm9r+AvheXAJ7CJASFSVyXJq+tWXjRutkrvaBpKzx2Z6iw0EWkVVl4bVPAGJozfhrRADNsD9yPZWY4ff3qqn34o=
    - secure: gEbMsr7aBa7eBZA4vlYi5NxHJYnJHdyTlPCdLLE90+B9i8a6a0J1/U5nhy3GlW4DeufXQjCqzY4tDQNvvHOzsAwYQGtFXCkNptzlpL/dAqScRWq61bl7VO6Zplq3AX2dIlQJdr09rKQKL1QqBcxxOZeNGG32vdA0GuGnRJHxA7rr4M218UY/KPR0u5ijrPVll8QtAPx2vzx1+EoIQ677ppRYE9oDXfeu3c9NvRCR5Lk4Iq8hXBIRLtEZrVtKzoAIf/9SoOCn3gK0/yT4NuOn+EDkJzVSK1bS0GMLnBUR5HY27/uNfugwFgLFlVILzvceRDVTaFbov0+jT2B8gH4LM6M9b0K1Fhd/eaIcgSJ/gcKc+bbvaihoXySXtFmQaCxzo/qqgdY5g4kZamENfxMYeutl2Tanno7qsIsjs2Lz2UTh1mP03zIjCJu8rMMJCgf3Ql++fVtq98Rrgg2ZpLOdrwLB1RtJ7BaXS8ZCDJ4db8xOEFd8rwadClMpK7bCaRb5uLr5LX5jh7rHypGmf+m5kAdBmeyDvdw/zQ/u/8Q44acm+O0IaDMoE453pbAMY7hmt4aKOsQHM1sX5F8X44E9Y8HzQfb1ku/DTAsigPjaqVlxNXEJkqSbv7sZSk6J6tdYbnVwPWThGNiVB7Mw7bS0i3xs+q7+n9DX97lJPU3XAbw=
    # LTD Keeper / S3 deployment credentials and configs
    - secure: "arWTnvRF6DiXyGai0emJ36olQJGqHJKBe5B96yhGMtdeZwCSfhbRPCIPF5p09CLs49os5uRBR2OgOLRqVYjWXYcw5vrPNPy++O0EBmmbKkUgWXiphbeqQD/1neRNSV1Yol3ZsTshcMGEx2JGBa77gd6svUGICD4rPUjw77NgvhMl5w2hhmf96tWc3Pq3kvhlBDFmvcdS6mO/M7UeZxYEFCzld5PPYPhK2SJTwFPji21nR/nGindUdsfyyIcnCAhXid1haF235wCqEo+SCUIQT6VhW3EPK/X8DbO+CRo1Abav5Xc2cG04SafVALOQIbel+aM29m7U1G5AmVtjs4pJ51QRa2954ADJFJSUV2WBO57025V57NEvQZi8CqyD0SFdtDhW4iYGN1ZiN1FIU/r1YCzXOff5DHb6i0IO5SclDKGMF1XflsvbQZMsss7AKQ1jSVaPZpawCMW3qSO+pNkqkd6qeU2dWgxkGueyd5HbF3yJKFln6ekMU3wc6KDxoIkFrIOc65Y013m/ACR4/l45F//vWK0AMS89gZp5gEvXgIeceJ2bjkZ0ile04FWp1BlOE5jm338BF6QijGakGy5/0S4CXKdQVpvtB9YsjFdHGXuizheCPXhTneYDyhAEgl99DMda4UfaMiU5zkjDdZR5PCGLC1zCz/3+E402+OwoL+0="
    - secure: "ZRFGeZsyRTu8vKoe5/ro/cXl8MEBiFEOpyWi602w8IsIavklVu09/vVtzRfYSQ5MdvCD1XiSR+tcmD8Zpu0SOc87PZNRRvVzAdpAop/7LJP9KGd5QSHs+LdQZfQme06R2OLLPVizq0buPn2AY90i/z3zgUp7roT2efQlVUAcjQFlwWROZdAPU4m42Dg8xmefzvORcrcGVQ4lAoNsIPiWVTt3jNTv8/iemFe0QH1MaBWhKjsUN/vcacoxJ+GQPq39ZWK7M9VaSIngZ0bHaz9CgvDQuIvsYWTq4bYfjBBz7GPKyfxfdMKh2CRoTlBITMJJ1ddHY4zh9gi6oDhDXZefSqi6fJ3AcXdWnF5mnmQ+xYrvnsdLyOjFFfnvJVEEpEM34vfRQWNkw+Z+bXRFB6MglJBCouiEEfbZhGWOg//fE/ep5IKGSzqPkeyEVubGJYsfK72oPe/Sy+nEQsnck9gX+UWUPwAREAOew620dFxdx+09aXFN1v5X85uuLzwmwYJvfK6PNFshcYABAFKjkVZqcls2udM6Rcp4Ld+Nyur42it8kmjAlvbccU3TVIqEI7yKUefoSgj49fgoxPa1/2Fed9OON74OXXvN5p53CWovwvzQoIDSGNshmUrOu+dc9nQCkjnl71WaEG+RWSLfVz5F9ZQVef/FPmrYEliqVwTHh1g="
