[project]
title = "LTD Conveyor"
copyright = "2017–2023 Association of Universities for Research in Astronomy, Inc. (AURA)"

[project.python]
package = "ltd-conveyor"

[sphinx]
rst_epilog_file = "_rst_epilog.rst"
disable_primary_sidebars = [
    "index",
    "changelog",
]
extensions = [
    "sphinx_click.ext"
]

[sphinx.intersphinx.projects]
python = "https://docs.python.org/3/"
boto3 = "http://boto3.readthedocs.io/en/latest/"
