name: Python CI

"on":
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - "dependabot/**"
      - "renovate/**"
      - "tickets/**"
      - "u/**"
    tags:
      - "*"
  pull_request: {}

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full depth for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        env:
          LTD_TEST_AWS_ID: ${{ secrets.LTD_TEST_AWS_ID }}
          LTD_TEST_AWS_SECRET: ${{ secrets.LTD_TEST_AWS_SECRET }}
          LTD_TEST_BUCKET: ${{ secrets.LTD_TEST_BUCKET }}
        run: tox -e py,lint,typing  # run tox using Python in path

  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full depth for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install tox
        run: |
          pip install tox

      - name: Run tox
        run: tox -e docs

      - name: Install LTD Conveyor for upload
        run: pip install .

      - name: Upload to LSST the Docs
        if: env.LTD_USERNAME != null
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product ltd-conveyor --gh --dir docs/_build/html

  pypi:

    runs-on: ubuntu-latest
    needs: [test, docs]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full depth for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel

      - name: Build
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_SQRE_ADMIN }}
        run: python setup.py sdist bdist_wheel

      - name: Upload
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_SQRE_ADMIN }}
